development:
  host: localhost
  database: proto2_development

test:
  host: localhost
  database: proto2_test

# set these environment variables on your prod server
production:
    uri: <%= ENV['MONGOHQ_URL'] %>
    username: heroku
    database: proto2  
    #host: localhost
    #database: proto2_production
    
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
